services:
  - type: web
    name: travel-tribe
    env: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn travel_tribe.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: travel-tribe-db
          property: connectionString

databases:
  - name: travel-tribe-db
    databaseName: travel_tribe
    user: travel_tribe_user
