# Generated by Django 5.2.6 on 2025-11-12 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('media_file', models.FileField(blank=True, help_text='Upload image or video', null=True, upload_to='chat_media/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.chatroom')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tribe_count', models.PositiveIntegerField(default=1)),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Both', 'Both')], default='Both', max_length=10)),
                ('category', models.CharField(choices=[('Within Country', 'Within Country'), ('Outside Country', 'Outside Country')], default='Within Country', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short overview about this trip.')),
                ('main_image', models.ImageField(blank=True, help_text='Main image for the trip.', null=True, upload_to='trip_images/')),
                ('transport_modes', models.CharField(blank=True, help_text='Available transport options (e.g., Train, Flight, Bus, Car).', max_length=200)),
                ('must_visit_places', models.TextField(blank=True, help_text='Comma-separated list of must-visit places.')),
                ('must_try_foods', models.TextField(blank=True, help_text='Comma-separated list of must-try local foods.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trip_gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('interests', models.CharField(choices=[('Adventure', 'Adventure'), ('Relaxation', 'Relaxation'), ('Food', 'Food'), ('Culture', 'Culture'), ('Photography', 'Photography'), ('Friends', 'Friends'), ('Solo', 'Solo')], max_length=100)),
                ('gender_preference', models.CharField(choices=[('Any', 'Any'), ('Male', 'Male'), ('Female', 'Female')], default='Any', max_length=20)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('members_limit', models.PositiveIntegerField(default=5)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joined_members', models.ManyToManyField(blank=True, related_name='joined_trips', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='trip_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='main.trippost'),
        ),
    ]
