# Generated by Django 5.2.6 on 2025-11-12 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='joined_members',
            field=models.ManyToManyField(blank=True, related_name='joined_destination_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='members_limit',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of members'),
        ),
    ]
