# Generated by Django 5.2.6 on 2025-11-20 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_join_request_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='main.trip'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='trip_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='main.trippost'),
        ),
    ]
