# Generated by Django 5.2.6 on 2025-11-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chatroom_trip_alter_chatroom_trip_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='user',
        ),
        migrations.DeleteModel(
            name='JoinRequest',
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
