# Generated by Django 5.2.6 on 2025-11-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_passwordresetotp_user_delete_joinrequest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
    ]
