# Generated by Django 5.2.6 on 2025-11-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_trip_is_featured_trip_requires_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='requires_approval',
        ),
        migrations.DeleteModel(
            name='FeaturedTripRequest',
        ),
    ]
