# Generated by Django 5.2.6 on 2025-11-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_trip_requires_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='is_featured',
        ),
    ]
