# Generated by Django 5.2.6 on 2025-12-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_is_featured'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: schema_editor.execute(
                """
                DO $$ 
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='main_userprofile' AND column_name='badges') THEN
                        ALTER TABLE main_userprofile DROP COLUMN badges;
                    END IF;
                    
                    IF EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='main_userprofile' AND column_name='level') THEN
                        ALTER TABLE main_userprofile DROP COLUMN level;
                    END IF;
                    
                    IF EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='main_userprofile' AND column_name='points') THEN
                        ALTER TABLE main_userprofile DROP COLUMN points;
                    END IF;
                END $$;
                """
            ) if schema_editor.connection.vendor == 'postgresql' else None,
            reverse_code=migrations.RunPython.noop
        ),
    ]
